import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Rydvest",
  description: "Read Rydvest's terms of service before investing.",
};

const sections = [
  {
    title: "1. About Rydvest",
    content: ` Rydvest is a legally registered Nigerian company, incorporated with the Corporate Affairs Commission (CAC) as Rydvest Ltd (RC 9771506). We follow strict anti-money-laundering and customer verification practices, and we are committed to transparency, integrity and accountability in everything we do. We provide a structured platform that allows individuals to invest in commercial transport vehicles and earn returns over a specified investment term.

By accessing or using the Rydvest platform — whether through our website, mobile application, or any associated service — you agree to be bound by these Terms of Service. If you do not agree, please do not use our platform.`,
  },
  {
    title: "2. Eligibility",
    content: `To use Rydvest, you must:

— Be at least 18 years of age
— Be a resident of Nigeria or hold a valid Nigerian bank account
— Provide accurate and verifiable personal information during registration
— Not be acting on behalf of any person or entity for the purpose of money laundering, fraud, or any other illegal activity

By creating an account, you confirm that all information you provide is true, accurate, and up to date.`,
  },
  {
    title: "3. How Investment Works",
    content: `Rydvest offers three investment structures:

Full Ownership — You fund the full cost of a vehicle yourself. You are the sole investor on that vehicle for the duration of the specified investment term.

Public Pool — You contribute a minimum amount to an open investment pool alongside other investors on the platform. Once the pool reaches its funding target, the vehicle is acquired and deployed, and returns begin for the specified term.

Private Pool — You create or join an invitation-only pool with people you trust — family, friends, or a cooperative. The pool functions the same way as a public pool once fully funded.

In all cases, Rydvest acquires the vehicle, assigns a vetted driver, manages all operations, and pays returns directly to your registered bank account at the frequency specified at the time of investment.`,
  },
  {
    title: "4. Returns and Payouts",
    content: `The return rate and payout frequency that apply to your investment are clearly displayed on the platform at the time you fund your position. These terms are locked in at the point of funding and will not change during your active investment cycle.

Rydvest processes payouts directly to the bank account you registered and verified on the platform. We do not hold your returns beyond the scheduled processing date.

Returns are derived from operational revenue generated by deployed vehicles. Rydvest does not guarantee returns beyond what is stated at the time of your investment. In the event of unforeseen operational disruption, Rydvest will communicate directly with affected investors.`,
  },
  {
    title: "5. Investment Capital and Weekly Payouts",
    content: `Your investment with Rydvest is structured over a 78-week investment term. During this period, your investment capital is paired with your applicable profit and distributed to you through weekly payouts.

This means that your investment capital is not held separately until the end of the 78-week term. Instead, the applicable portion of your capital, together with the corresponding weekly profit, forms part of your scheduled weekly payout throughout the investment period.

Provided the investment remains active and is not subject to an approved early withdrawal, dispute, account restriction, or other verified issue, you will receive your scheduled weekly payouts according to the terms of your selected investment plan.

At the completion of the 78-week investment term, the scheduled repayment of your investment capital will have been completed through the weekly payouts, alongside the applicable profits due under your investment plan.

If you wish to withdraw before the completion of the 78-week term, your request will be handled in accordance with Rydvest’s applicable Withdrawal Policy. Early withdrawal may be subject to processing timelines, eligibility requirements, applicable conditions, or other adjustments specified under the policy.
The specific terms applicable to your early withdrawal request will be communicated to you at the time of the request.Rydvest reserves the right to review accounts where there are outstanding disputes, suspected irregularities, payment issues, or other verified matters that may affect the processing of a payout or withdrawal.`,
  },
  {
    title: "6. Internal Transfer Feature",
    content: `Rydvest provides an internal transfer feature that allows registered users to transfer eligible funds from their available dashboard balance to another registered Rydvest user.

6.1 Unique Rydvest User ID

Each registered user will be assigned a unique Rydvest User ID. This ID will be used to identify the intended recipient of an internal transfer.

Users may share their Rydvest User ID for the purpose of receiving funds. Passwords, transaction PINs, one-time passwords and other security credentials must not be shared with anyone.

6.2 Eligible Funds

Only funds reflected as available and transferable in a user’s dashboard balance may be transferred. The following funds may not be eligible for transfer:

— Funds subject to an active lock
— Pending capital or profit distributions
— Funds under review, dispute or restriction
— Promotional bonuses with transfer limitations
— Funds reserved for outstanding obligations
— Any other balance classified by Rydvest as non-transferable

6.3 Recipient Verification

Before authorizing a transfer, the sender must enter the recipient’s correct Rydvest User ID and verify the recipient information displayed on the confirmation page.

The sender is solely responsible for confirming that the recipient’s details, transfer amount and transaction information are correct before approving the transfer.

6.4 Transfer Authorization

A transfer confirmed using the sender’s password, transaction PIN, one-time password, biometric verification or any other approved security method will be treated as an authorized transaction.

Users must not authorize a transfer unless they have reviewed and confirmed all transaction details.

6.5 Completion and Availability

Once successfully processed, the transferred amount will be deducted from the sender’s available balance and credited to the recipient’s Rydvest dashboard balance.

An internal transfer represents a movement of funds between balances maintained within the Rydvest platform. It is not a direct transfer to the recipient’s external bank account. The recipient may withdraw the credited funds in accordance with Rydvest’s withdrawal policy.

6.6 Transfer Finality and Incorrect Transfers

Completed internal transfers are generally final and cannot be automatically cancelled or reversed.

Where a sender transfers funds to an incorrect Rydvest User ID, the sender must immediately contact Rydvest Support. Rydvest may attempt to assist with recovery, but recovery is not guaranteed and may require the consent of the recipient.

Rydvest will not be responsible for losses resulting from incorrect recipient details entered or confirmed by the sender, except where the loss is directly caused by a verified system error attributable to Rydvest.

6.7 Transfer Limits and Charges

Rydvest may establish minimum or maximum transfer amounts, daily transaction limits, frequency limits or applicable transfer charges.

Any applicable fee or restriction will be displayed to the sender before the transfer is confirmed. Rydvest may revise these limits or charges where reasonably necessary and will communicate material changes through the platform.

6.8 Compliance and Security Reviews

Rydvest may delay, restrict, reject, suspend or reverse a transfer where reasonably necessary to:

— Protect a user’s account
— Investigate suspected fraud or unauthorized activity
— Correct a verified technical or processing error
— Comply with applicable laws, court orders or regulatory obligations
— Complete identity, source-of-funds or transaction verification
— Enforce platform limits or restrictions
— Protect Rydvest, its users or third parties from loss or misuse

Users may be required to provide additional information or documentation before a restricted transfer is completed or released.

6.9 Prohibited Use

The internal transfer feature must not be used for fraud, money laundering, unlawful payments, unauthorized commercial activity or any transaction prohibited by law or Rydvest’s policies.

Rydvest may suspend or terminate access to the transfer feature where misuse or suspicious activity is identified.

6.10 Transaction Records

Completed and pending internal transfers will be recorded in the user’s transaction history. Users are responsible for reviewing their transaction records and promptly reporting any suspected unauthorized transfer or discrepancy to Rydvest Support.`,
  },
  {
    title: "7. Savings and Fund Locking Feature",
    content: `Rydvest may also offer an optional fund-locking feature that allows you to lock all or part of your available balance for a specified period. Before confirming a fund lock, the applicable duration, benefits, conditions and maturity date will be displayed to you. Funds placed under an active lock will generally remain unavailable for withdrawal until the agreed lock period expires, except where otherwise permitted under the applicable terms.

At the end of the lock period, the locked funds and any applicable benefits will be released to your available dashboard balance and may be withdrawn in accordance with Rydvest’s withdrawal policy.`,
  },
  {
    title: "8. Your Responsibilities",
    content: `You are responsible for:

— Keeping your account credentials secure and not sharing them with anyone
— Ensuring your registered bank account details are correct and up to date
— Notifying Rydvest immediately if you suspect unauthorised access to your account
— Not using the platform for any fraudulent, illegal, or abusive purpose
— Ensuring that any funds you invest are from legitimate sources

Rydvest reserves the right to suspend or terminate accounts that violate these responsibilities.`,
  },
  {
    title: "9. Rydvest's Responsibilities",
    content: `Rydvest is responsible for:

— Acquiring and deploying vehicles funded through the platform
— Vetting and onboarding drivers assigned to investor vehicles
— Managing all day-to-day operations including maintenance and insurance
— Processing return payments on schedule as specified at the time of investment
— Returning investor capital at the end of the specified investment term
— Communicating clearly with investors about any material changes to their investment

Rydvest is not responsible for delays caused by banking system failures, acts of God, government action, or events genuinely outside our control. In such cases, we will communicate with investors and resolve the situation as quickly as possible.`,
  },
  {
    title: "10. Risk Disclosure",
    content: `While we take all reasonable steps to protect your investment, you should be aware that:

— Commercial transport operations can be affected by accidents, theft, or damage
— Economic and regulatory conditions in Nigeria may change
— Returns are derived from operational revenue and are not guaranteed beyond what is stated at the time of your investment
— Early withdrawal may result in reduced returns

Rydvest is not a bank or a licensed financial institution. This platform is structured as an asset-backed co-investment arrangement. Please invest only what you can afford to commit for the full specified term.`,
  },
  {
    title: "11. Privacy",
    content: `Your personal data is collected and processed in accordance with our Privacy Policy. By using Rydvest, you consent to the collection and use of your information as described in that policy. We do not sell or share your personal data with third parties for marketing purposes.`,
  },
  {
    title: "12. Changes to These Terms",
    content: `Rydvest may update these Terms of Service from time to time. When we do, we will notify you via email or a prominent notice on the platform. Continued use of the platform after such updates constitutes your acceptance of the revised terms.`,
  },
  {
    title: "13. Governing Law",
    content: `These Terms are governed by the laws of the Federal Republic of Nigeria. Any dispute arising from your use of Rydvest that cannot be resolved through direct communication will be referred to the appropriate court or arbitration body in Anambra State, Nigeria.`,
  },
  {
    title: "14. Contact",
    content: `If you have questions about these Terms, please contact us at hello@rydvest.com or reach us on WhatsApp at +234 706 528 4100. We are also available at our office in Anambra State, Nigeria.`,
  },
];

export default function TermsPage() {
  return (
    <main className="bg-white min-h-screen">

      <div className="bg-[#0d2137] py-16 px-6">
        <div className="max-w-3xl mx-auto">
          <Link href="/" className="text-amber-400 text-sm font-semibold hover:text-amber-300 transition-colors mb-6 inline-flex items-center gap-2">
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
            </svg>
            Back to home
          </Link>
          
          <h1 className="text-3xl sm:text-4xl font-black text-white tracking-tight mb-3">Terms of Service</h1>
          <p className="text-slate-400 text-sm">Last updated: January 2026 · Rydvest Ltd, Anambra State, Nigeria</p>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <p className="text-slate-600 text-base leading-relaxed mb-12 p-5 bg-amber-50 border border-amber-100 rounded-xl">
          Please read these terms carefully before using the Rydvest platform. By creating an account or making an investment, you agree to everything written here. If anything is unclear, contact us before proceeding.
        </p>

        <div className="flex flex-col gap-10">
          {sections.map((s) => (
            <div key={s.title}>
              <h2 className="text-lg font-extrabold text-slate-900 mb-4">{s.title}</h2>
              <div className="text-slate-600 text-sm leading-relaxed whitespace-pre-line">{s.content}</div>
            </div>
          ))}
        </div>
      </div>

      <div className="border-t border-slate-100 py-8 px-6">
        <div className="max-w-3xl mx-auto flex flex-wrap gap-4 justify-between items-center">
          <span className="text-sm font-black text-slate-900">Ryd<span className="text-amber-400">vest</span></span>
          <div className="flex gap-5">
            <Link href="/privacy" className="text-xs text-slate-400 hover:text-slate-700 transition-colors">Privacy Policy</Link>
            <Link href="/faq" className="text-xs text-slate-400 hover:text-slate-700 transition-colors">FAQ</Link>
          </div>
        </div>
      </div>

    </main>
  );
}
