import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Ridvest",
  description: "Read Ridvest's terms of service before investing.",
};

const sections = [
  {
    title: "1. About Ridvest",
    content: `Ridvest is a transport co-investment platform operated by Ridvest Ltd, registered in Nigeria and headquartered in Ogidi, Anambra State. We provide a structured platform that allows individuals to invest in commercial vehicles and earn returns over a specified investment term.

By accessing or using the Ridvest platform — whether through our website, mobile application, or any associated service — you agree to be bound by these Terms of Service. If you do not agree, please do not use our platform.`,
  },
  {
    title: "2. Eligibility",
    content: `To use Ridvest, you must:

— Be at least 18 years of age
— Be a resident of Nigeria or hold a valid Nigerian bank account
— Provide accurate and verifiable personal information during registration
— Not be acting on behalf of any person or entity for the purpose of money laundering, fraud, or any other illegal activity

By creating an account, you confirm that all information you provide is true, accurate, and up to date.`,
  },
  {
    title: "3. How Investment Works",
    content: `Ridvest offers three investment structures:

Full Ownership — You fund the full cost of a vehicle yourself. You are the sole investor on that vehicle for the duration of the specified investment term.

Public Pool — You contribute a minimum amount to an open investment pool alongside other investors on the platform. Once the pool reaches its funding target, the vehicle is acquired and deployed, and returns begin for the specified term.

Private Pool — You create or join an invitation-only pool with people you trust — family, friends, or a cooperative. The pool functions the same way as a public pool once fully funded.

In all cases, Ridvest acquires the vehicle, assigns a vetted driver, manages all operations, and pays returns directly to your registered bank account at the frequency specified at the time of investment. At the end of the specified term, your original capital is returned in full.`,
  },
  {
    title: "4. Returns and Payouts",
    content: `The return rate and payout frequency that apply to your investment are clearly displayed on the platform at the time you fund your position. These terms are locked in at the point of funding and will not change during your active investment cycle.

Ridvest processes payouts directly to the bank account you registered and verified on the platform. We do not hold your returns beyond the scheduled processing date.

Returns are derived from operational revenue generated by deployed vehicles. Ridvest does not guarantee returns beyond what is stated at the time of your investment. In the event of unforeseen operational disruption, Ridvest will communicate directly with affected investors.`,
  },
  {
    title: "5. Capital Return",
    content: `Your original investment capital will be returned to you in full at the end of your specified investment term, provided you have not requested early withdrawal and there are no outstanding disputes or verified issues with your account.

Early withdrawal requests are subject to Ridvest's withdrawal policy, which may include processing timelines and applicable conditions. These details will be communicated to you at the time of your request.`,
  },
  {
    title: "6. Your Responsibilities",
    content: `You are responsible for:

— Keeping your account credentials secure and not sharing them with anyone
— Ensuring your registered bank account details are correct and up to date
— Notifying Ridvest immediately if you suspect unauthorised access to your account
— Not using the platform for any fraudulent, illegal, or abusive purpose
— Ensuring that any funds you invest are from legitimate sources

Ridvest reserves the right to suspend or terminate accounts that violate these responsibilities.`,
  },
  {
    title: "7. Ridvest's Responsibilities",
    content: `Ridvest is responsible for:

— Acquiring and deploying vehicles funded through the platform
— Vetting and onboarding drivers assigned to investor vehicles
— Managing all day-to-day operations including maintenance and insurance
— Processing return payments on schedule as specified at the time of investment
— Returning investor capital at the end of the specified investment term
— Communicating clearly with investors about any material changes to their investment

Ridvest is not responsible for delays caused by banking system failures, acts of God, government action, or events genuinely outside our control. In such cases, we will communicate with investors and resolve the situation as quickly as possible.`,
  },
  {
    title: "8. Risk Disclosure",
    content: `Investing through Ridvest carries risks. While we take all reasonable steps to protect your investment, you should be aware that:

— Commercial transport operations can be affected by accidents, theft, or damage
— Economic and regulatory conditions in Nigeria may change
— Returns are derived from operational revenue and are not guaranteed beyond what is stated at the time of your investment
— Early withdrawal may result in reduced returns

Ridvest is not a bank or a licensed financial institution. This platform is structured as an asset-backed co-investment arrangement. Please invest only what you can afford to commit for the full specified term.`,
  },
  {
    title: "9. Privacy",
    content: `Your personal data is collected and processed in accordance with our Privacy Policy. By using Ridvest, you consent to the collection and use of your information as described in that policy. We do not sell or share your personal data with third parties for marketing purposes.`,
  },
  {
    title: "10. Changes to These Terms",
    content: `Ridvest may update these Terms of Service from time to time. When we do, we will notify you via email or a prominent notice on the platform. Continued use of the platform after such updates constitutes your acceptance of the revised terms.`,
  },
  {
    title: "11. Governing Law",
    content: `These Terms are governed by the laws of the Federal Republic of Nigeria. Any dispute arising from your use of Ridvest that cannot be resolved through direct communication will be referred to the appropriate court or arbitration body in Anambra State, Nigeria.`,
  },
  {
    title: "12. Contact",
    content: `If you have questions about these Terms, please contact us at hello@ridvest.ng or reach us on WhatsApp at +234 800 000 0000. We are also available at our office in Ogidi, Anambra State, Nigeria.`,
  },
];

export default function TermsPage() {
  return (
    <main className="bg-white min-h-screen">

      <div className="bg-[#0d2137] py-16 px-6">
        <div className="max-w-3xl mx-auto">
          <Link href="/" className="text-amber-400 text-sm font-semibold hover:text-amber-300 transition-colors mb-6 inline-flex items-center gap-2">
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
            </svg>
            Back to home
          </Link>
          
          <h1 className="text-3xl sm:text-4xl font-black text-white tracking-tight mb-3">Terms of Service</h1>
          <p className="text-slate-400 text-sm">Last updated: January 2026 · Ridvest Ltd, Ogidi, Anambra State, Nigeria</p>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <p className="text-slate-600 text-base leading-relaxed mb-12 p-5 bg-amber-50 border border-amber-100 rounded-xl">
          Please read these terms carefully before using the Ridvest platform. By creating an account or making an investment, you agree to everything written here. If anything is unclear, contact us before proceeding.
        </p>

        <div className="flex flex-col gap-10">
          {sections.map((s) => (
            <div key={s.title}>
              <h2 className="text-lg font-extrabold text-slate-900 mb-4">{s.title}</h2>
              <div className="text-slate-600 text-sm leading-relaxed whitespace-pre-line">{s.content}</div>
            </div>
          ))}
        </div>
      </div>

      <div className="border-t border-slate-100 py-8 px-6">
        <div className="max-w-3xl mx-auto flex flex-wrap gap-4 justify-between items-center">
          <span className="text-sm font-black text-slate-900">Rid<span className="text-amber-400">vest</span></span>
          <div className="flex gap-5">
            <Link href="/privacy" className="text-xs text-slate-400 hover:text-slate-700 transition-colors">Privacy Policy</Link>
            <Link href="/faq" className="text-xs text-slate-400 hover:text-slate-700 transition-colors">FAQ</Link>
          </div>
        </div>
      </div>

    </main>
  );
}
